name: Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x' # or the version you are using

      - name: Publish
        run: dotnet publish -c Release -o ./published

      - name: Copy files via SCP
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          $username = "${{ secrets.SERVER_USER }}"
          $password = "${{ secrets.SERVER_PASSWORD }}"
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

          $sourcePath = "./published/*"
          $targetPath = "C:/Users/Jared/Documents/GitHub/MovieReviewApp/publish"

          $sessionOptions = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck

          $session = New-PSSession -HostName "${{ secrets.SERVER_HOST }}" -UserName $username -Credential $credential -UseSSL -SessionOption $sessionOptions

          Invoke-Command -Session $session -ScriptBlock {
            param($sourcePath, $targetPath)
            if (!(Test-Path -Path $targetPath)) {
              New-Item -ItemType Directory -Force -Path $targetPath
            }
            Copy-Item -Path $using:sourcePath -Destination $targetPath -Recurse -Force
          } -ArgumentList $sourcePath, $targetPath

          Remove-PSSession -Session $session

      - name: Restart application
        shell: pwsh
        run: |
          $username = "${{ secrets.SERVER_USER }}"
          $password = "${{ secrets.SERVER_PASSWORD }}"
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

          $sessionOptions = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck

          $session = New-PSSession -HostName "${{ secrets.SERVER_HOST }}" -UserName $username -Credential $credential -UseSSL -SessionOption $sessionOptions

          Invoke-Command -Session $session -ScriptBlock {
            Stop-Process -Name "MovieReviewApp" -Force -ErrorAction SilentlyContinue
            Start-Process "C:/Users/Jared/Documents/GitHub/MovieReviewApp/publish/MovieReviewApp.exe"
          }

          Remove-PSSession -Session $session
